spring.application.name=Hospital_management

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=pass

#jakarta (jpa) some optional settings
#This will create schema on running your application and will also drop all schemas once you stop your application
spring.jpa.hibernate.ddl-auto=update
#TO see all the sql statements runned by hibernate
spring.jpa.show-sql=true
#Format the hibernate queries, statements
spring.jpa.properties.hibernate.format_sql=true